#!/usr/bin/env bash
cli_log() {
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "== $script_name $timestamp $1"
}

get_os() {
    case "$OSTYPE" in
      solaris*) echo "SOLARIS" ;;
      darwin*)  echo "OSX" ;; 
      linux*)   echo "LINUX" ;;
      bsd*)     echo "BSD" ;;
      msys*)    echo "WINDOWS" ;;
      *)        echo "unknown: $OSTYPE" ;;
    esac
}

date_func() {
    case "$TODO_OS" in 
        LINUX)
            echo "date" ;;
        OSX)
            echo "gdate" ;;
    esac
}

export TODO_OS=$(get_os)
export TODO_DATE_FUNC=$(date_func)
