#!/usr/bin/env bash
set -e
. "$TODO_WORKDIR/common"

cli_help_deploy() {
  echo "
Command: deploy
Usage: 
  deploy project_name"
  exit 1
}

[ ! -n "$1" ] && cli_help_deploy

export TODO_PROJECT_NAME=$1

cli_log "Deployment BEGIN"

cli_log "ENV variables"
env | grep "TODO_*"

cli_log "Executing helm upgrade --install ..."
# Example
# helm upgrade --install \
#   --wait \
#   --values $TODO_PROJECTS_PATH/$TODO_PROJECT_NAME/values.yaml \
#   --namespace $TODO_K8S_NAMESPACE $TODO_PROJECT_NAME $TODO_REPO_PATH

cli_log "Deployment END"
