#!/usr/bin/env bash
# set -e
. "$TODO_WORKDIR/common"

cli_help_day() {
  echo "
Command: tomorrow
Usage: 
  tomorrow"
  exit 1
}

[ -n "$1" ] && cli_help_day


DAY='tomorrow'
DAY_LONG=$($TODO_DATE_FUNC -d $DAY)

todo d $DAY
