#!/usr/bin/env bash
# set -e
. "$TODO_WORKDIR/common"

cli_help_day() {
  echo "
Command: tomorrow
Usage: 
  tomorrow"
  exit 1
}

[ -n "$1" ] && cli_help_day


DAY='tomorrow'
DAY_FILE="$HOME/todo/$DAY.txt"
DAY_LONG=$($TODO_DATE_FUNC -d $DAY)

todo d $DAY

# Example
# helm upgrade --install \
#   --wait \
#   --values $TODO_PROJECTS_PATH/$TODO_PROJECT_NAME/values.yaml \
#   --namespace $TODO_K8S_NAMESPACE $TODO_PROJECT_NAME $TODO_REPO_PATH
